name: Build Package

on: [push]

jobs:
  build:

    runs-on: macos-latest    

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=15.0
    - name: Setup .NET Core SDK 9.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.x'

    - name: Install dependencies
      run: nuget restore BarcodeScanner.Mobile.Maui/BarcodeScanner.Mobile.Maui.csproj

    - name: Build
      run: dotnet BarcodeScanner.Mobile.Maui/BarcodeScanner.Mobile.Maui.csproj /p:Configuration=Release

    - name: Nuget Push
      run: nuget push BarcodeScanner.Mobile.Maui/bin/Release/*.nupkg -Source https://nuget.pkg.github.com/stepkillah/index.json -ApiKey ${{secrets.GITHUB_TOKEN}} -SkipDuplicate -NoSymbols
