name: Build Package

on: [push]

jobs:
  build:

    runs-on: macos-latest    

    steps:
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --android=11.1
    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore GoogleVisionBarCodeScanner/GoogleVisionBarCodeScanner.csproj

    - name: Build
      run: msbuild GoogleVisionBarCodeScanner/GoogleVisionBarCodeScanner.csproj /p:Configuration=Release
   
    - name: Nuget Pack
      run: nuget pack GoogleVisionBarCodeScanner/GoogleVisionBarCodeScanner.csproj -OutputDirectory ./nuget_pack

    - name: Nuget Push
      run: nuget push ./nuget_pack/*.nupkg -Source https://nuget.pkg.github.com/stepkillah/index.json -ApiKey ${{secrets.GITHUB_TOKEN}} -SkipDuplicate -NoSymbols
